### ISSUE TITLE
Design the Home Screen 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/StoryBook-RN#2]
### Tasks : 

- Create an appealing UI for the Home Screen
- Customizing the existing design is appreciated

**Comment by AyushSinghbharti** [comment]
Hello @pooranjoyb I would like to contribute in this project, please assign this issue to me

**Comment by pooranjoyb** [comment]
> Hello @pooranjoyb I would like to contribute in this project, please assign this issue to me

Hey @AyushSinghbharti  will assign this issue once JWOC 2024 phase 1 starts! 😄
Don't forget to Star ⭐ the Repository :)))

**Comment by pooranjoyb** [comment]
@gayathrik23 Assigned! Go ahead, you have 24 hours to raise a PR for this issue. 🚀

**Comment by AyushSinghbharti** [comment]
Hello @pooranjoyb I would like to contribute in this issue, please assign this issue to me too!!!

**Comment by pooranjoyb** [comment]
> Hello @pooranjoyb I would like to contribute in this issue, please assign this issue to me too!!!

Assigned @AyushSinghbharti 
Go for it! 💯

**Comment by AyushSinghbharti** [comment]
@pooranjoyb Do I still have to redesign home screen?
I have already designed UI in the 1st pull request so do I still have to design homescreen as this issue is still open?  


![Screenshot_2024-01-16-20-30-40-57_f73b71075b1de7323614b647fe394240](https://github.com/pooranjoyb/StoryBook-RN/assets/100284852/8218096f-bf80-45cc-b434-8b20d0557c60)

**Comment by pooranjoyb** [comment]
No it's okay, No need to design it as of now. @AyushSinghbharti
